# Generated by Django 4.1.3 on 2022-11-13 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Productos',
            new_name='Inventario',
        ),
    ]
