# Generated by Django 4.1.3 on 2022-11-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_alter_artículo_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coleccion',
            old_name='tipos_prenda_col',
            new_name='tipo_de_prenda',
        ),
    ]
