# Generated by Django 4.1.3 on 2022-11-24 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0005_rename_tipos_prenda_col_coleccion_tipo_de_prenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='artículo',
            name='colec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuenta.coleccion'),
        ),
    ]
