# Generated by Django 4.1.3 on 2022-11-24 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0006_artículo_colec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artículo',
            name='colec',
        ),
        migrations.AddField(
            model_name='artículo',
            name='coleccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cuenta.coleccion'),
        ),
    ]
