# Generated by Django 4.1.3 on 2022-11-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0009_rename_carrocompras_carrocompra'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='artículo',
            old_name='cant_disponible_por_talla',
            new_name='cant_disponible_L',
        ),
        migrations.RemoveField(
            model_name='artículo',
            name='talla',
        ),
        migrations.AddField(
            model_name='artículo',
            name='cant_disponible_M',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artículo',
            name='cant_disponible_S',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artículo',
            name='cant_disponible_XL',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artículo',
            name='cant_disponible_XS',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
