# Generated by Django 4.1.3 on 2022-11-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0010_albumfoto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlbumFoto',
        ),
        migrations.RenameField(
            model_name='artículo',
            old_name='fotos',
            new_name='foto1',
        ),
        migrations.AddField(
            model_name='artículo',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='artículo',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='artículo',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='artículo',
            name='precio',
            field=models.FloatField(),
        ),
    ]
