# Generated by Django 4.1.3 on 2022-11-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0012_direccionenvio'),
    ]

    operations = [
        migrations.AddField(
            model_name='artículo',
            name='oferta',
            field=models.BooleanField(default=False),
        ),
    ]
