# Generated by Django 4.1.3 on 2022-11-28 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0012_direccionenvio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccionenvio',
            name='user',
        ),
    ]
