# Generated by Django 4.1.3 on 2022-11-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0013_artículo_oferta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artículo',
            name='foto1',
            field=models.ImageField(upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='artículo',
            name='foto2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='artículo',
            name='foto3',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
        migrations.AlterField(
            model_name='artículo',
            name='foto4',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
