# Generated by Django 4.1.3 on 2022-11-29 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0014_alter_artículo_foto1_alter_artículo_foto2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artículo',
            name='tipo_articulo',
            field=models.CharField(choices=[('', 'Prendas superiores'), ('', 'Prendas inferiores')], max_length=200),
        ),
    ]
