# Generated by Django 4.1.3 on 2022-11-29 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0015_alter_artículo_tipo_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artículo',
            name='tipo_articulo',
            field=models.CharField(choices=[('', 'Prendas superiores'), ('', 'Prendas inferiores')], default='', max_length=200),
        ),
    ]
