# Generated by Django 4.1.3 on 2022-11-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0016_alter_artículo_tipo_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artículo',
            name='tipo_articulo',
            field=models.CharField(choices=[('Prendas superiores', 'Prendas superiores'), ('Prendas inferiores', 'Prendas inferiores')], default='Prendas superiores', max_length=200),
        ),
    ]
