# Generated by Django 4.1.3 on 2022-11-30 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0015_direccionenvio_user'),
        ('cuenta', '0017_alter_artículo_tipo_articulo'),
    ]

    operations = [
    ]
