# Generated by Django 4.1.3 on 2022-12-02 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0018_merge_20221130_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artículo',
            name='color',
        ),
        migrations.AlterField(
            model_name='artículo',
            name='foto5',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes'),
        ),
    ]
